development:
  adapter: postgresql
  encoding: utf8
  database: hotlynx_development
  pool: 5
  username: johnvanarkelen
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: hotlynx_test
  pool: 5
  username: johnvanarkelen
  password: